stages:
  - preflight
  - publish
  
install-pandoc:
  stage: preflight
  script: |
    wget --quiet --output-document=".pandoc-latest-amd64.deb" $(wget -qO - https://api.github.com/repos/jgm/pandoc/releases | grep browser_download_url | grep '64[.]deb' | head -n 1 | cut -d '"' -f 4)
    dpkg -i .pandoc-latest-amd64.deb

link-workflow:
  stage: preflight
  script: |
    mkdir -p .pandoc/include
    touch .pandoc/include/after-body.html
    echo -e "<hr />\n<p style=\"font-size: small; font-style: italic;\">\n\t<a href=\"https://www.gitlab.com/01001010/publi.sh\" target=\"_blank\">publi.sh</a> &rarr; <a href=\"$CI_PIPELINE_URL\" target=\"_blank\">$(echo $CI_COMMIT_SHA | cut -c 1-7)</a>\n</p>" >> .pandoc/include/after-body.html

pages:
  artifacts:
    paths:
      - "public"
  only:
    - main
  stage: publish
  script: |
    wget -qO - https://gitlab.com/01001010/publi-sh/-/raw/main/publi.sh | bash -s -- \
    -i README.md \
    -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css" \
    -p "--from=markdown+backtick_code_blocks+definition_lists+emoji+fancy_lists+fenced_code_attributes+line_blocks+markdown_in_html_blocks+task_lists+yaml_metadata_block" \
    -p "--include-after-body=.pandoc/include/after-body.html" \
    -p "--include-before-body=.pandoc/include/before-body.html" \
    -p "--include-in-header=.pandoc/include/in-header.html" \
    -p "--quiet" \
    -p "--standalone" \
    -p "--template=.pandoc/templates/default.html" \
    -p "--title-prefix=subcurmudgeon" \
    -p "--to=html" \
    -v \
    . \
    public