name: Publi.sh

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Preflight
        run: |
          sudo apt-get install pandoc
          mkdir .site
      - name: Publi.sh
        run: |
          curl -L -s https://raw.githubusercontent.com/jeremy-r-mayer/publi.sh/main/publi.sh | bash -s -- \
          -i README.md \
          -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1/new.min.css" \
          -v \
          . \
          .site
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: .site
          fqdn: www.01001010.net
          jekyll: false
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
