name: Publi.sh

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install the latest pandoc package from Github because the OS archives are always out of date.
      # https://github.com/jgm/pandoc
      - name: Pandoc
        run: |
          wget --quiet --output-document=".pandoc-latest-amd64.deb" $(wget -qO - https://api.github.com/repos/jgm/pandoc/releases | grep browser_download_url | grep '64[.]deb' | head -n 1 | cut -d '"' -f 4)
          sudo dpkg -i .pandoc-latest-amd64.deb

      # Run the latest version of publi.sh from Github with any necessary arguments.
      # https://github.com/subcurmudgeon/publi.sh
      - name: Publi.sh
        run: |
          wget -qO - https://raw.githubusercontent.com/subcurmudgeon/publi.sh/main/publi.sh | bash -s -- \
          -i README.md \
          -p "--css=https://fonts.xz.style/serve/inter.css" \
          -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css" \
          -p "--from=markdown+backtick_code_blocks+definition_lists+emoji+fancy_lists+fenced_code_attributes+line_blocks+markdown_in_html_blocks+task_lists+yaml_metadata_block" \
          -p "--include-after-body=.pandoc/include/after-body.html" \
          -p "--include-before-body=.pandoc/include/before-body.html" \
          -p "--include-in-header=.pandoc/include/in-header.html" \
          -p "--quiet" \
          -p "--standalone" \
          -p "--template=.pandoc/templates/default.html" \
          -p "--title-prefix=subcurmudgeon" \
          -p "--to=html" \
          -v \
          . \
          .site
      
      # Deploy final output to Github Pages.
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.subcurmudgeon.com
          publish_dir: .site
