name: Publi.sh

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preflight
        run: |
          sudo apt-get --no-install-recommends install pandoc
          mkdir .site

      - name: Publish
        run: |
          curl https://raw.githubusercontent.com/subcurmudgeon/publi.sh/main/publi.sh | bash -s -- \
          -i README.md \
          -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1/new.min.css" \
          -p "--from=markdown+backtick_code_blocks+definition_lists+emoji+fancy_lists+fenced_code_attributes+line_blocks+markdown_in_html_blocks+yaml_metadata_block" \
          -p "--include-after-body=.pandoc/include/after-body.html" \
          -p "--include-before-body=.pandoc/include/before-body.html" \
          -p "--include-in-header=.pandoc/include/in-header.html" \
          -p "--quiet" \
          -p "--standalone" \
          -p "--template=.pandoc/templates/default.html" \
          -p "--to=html" \
          -v \
          . \
          .site
      
      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.subcurmudgeon.com
          publish_dir: .site
