# This is a basic workflow to help you get started with Actions

name: Publi.sh

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: preflight
        run: |
          sudo apt-get install pandoc
          mkdir ./public
      - name: Publi.sh
        run: |
          ./publi.sh \
          -o \
          -i README.md \
          -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1/new.min.css" \
          -p "--number-sections" \
          -p "--quiet" \
          -p "--section-divs" \
          -p "--toc" \
          -p "--toc-depth=2" \
          -v \
          . \
          ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          destination_dir: ../
