name: Publi.sh

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Preflight - Update Workspace
        run: sudo apt-get update
      - name: Preflight - Install Dependancies
        run: sudo apt-get --no-install-recommends install pandoc
      - name: Publi.sh
        run: |
          .publi.sh/publi.sh \
          -i README.md \
          -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1/new.min.css" \
          -v \
          . \
          .site
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.subcurmudgeon.com
          publish_dir: .site
