name: Publi.sh

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preflight - System Update
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends install pandoc

      - name: Preflight - Checkout Submodules
        run: git submodule update --init --recursive

      - name: Publish
        run: |
          .publi.sh/publi.sh \
          -i README.md \
          -p "--css=https://cdn.jsdelivr.net/npm/@exampledev/new.css@1/new.min.css" \
          -v \
          . \
          .site
      
      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.subcurmudgeon.com
          publish_dir: .site
